name       : perl-xmlparser
version    : 2.44
release    : 5
source     :
    - http://search.cpan.org/CPAN/authors/id/T/TO/TODDR/XML-Parser-2.44.tar.gz : 1ae9d07ee9c35326b3d9aad56eae71a6730a73a116b9fe9e8a4758b7cc033216
license    :
    - Artistic-Perl-1.0
summary    : XML Parsing Module for Perl
component  : system.devel
builddeps  :
    - perl
description: |
    A Perl Module to parse XML
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
